defmodule PronotexWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :pronotex

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_pronotex_key",
    signing_salt: "M2Sv5JIT",
    same_site: "Lax",
    max_age: 60 * 60,
    secure: Application.compile_env(:pronotex, :secure_cookies, false)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug :session_cookie_lifetime
  plug Plug.Session, @session_options
  plug :protect_local_avatars

  plug Plug.Static,
    at: "/",
    from: :pronotex,
    gzip: not code_reloading?,
    only: PronotexWeb.static_paths(),
    # Production asset URLs include a digest before the extension.
    only_matching: ~w(manifest-),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug PronotexWeb.Router

  defp session_cookie_lifetime(conn, _) do
    register_before_send(conn, fn conn ->
      case {conn.resp_cookies["_pronotex_key"], conn.private[:plug_session]} do
        {%{value: value, max_age: age} = cookie, %{"auth_expires_at" => expires}} when age > 0 ->
          opts = cookie |> Map.delete(:value) |> Map.delete(:universal_time) |> Map.to_list()

          put_resp_cookie(
            conn,
            "_pronotex_key",
            value,
            Keyword.put(opts, :max_age, max(expires - Pronotex.Auth.now(), 0))
          )

        _ ->
          conn
      end
    end)
  end

  defp protect_local_avatars(%{path_info: ["images", "avatars" | _]} = conn, _) do
    conn = conn |> fetch_session() |> PronotexWeb.Auth.call([])

    cond do
      conn.halted -> conn
      PronotexWeb.Auth.avatar_allowed?(conn, conn.request_path) -> conn
      true -> conn |> send_resp(404, "") |> halt()
    end
  end

  defp protect_local_avatars(conn, _), do: conn
end
