defmodule PronotexWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :pronotex

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_pronotex_key",
    signing_salt: "M2Sv5JIT",
    same_site: "Lax",
    secure: Application.compile_env(:pronotex, :secure_cookies, false)
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Session, @session_options
  plug :protect_local_avatars

  plug Plug.Static,
    at: "/",
    from: :pronotex,
    gzip: not code_reloading?,
    only: PronotexWeb.static_paths(),
    # Production asset URLs include a digest before the extension.
    only_matching: ~w(manifest-),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug PronotexWeb.Router

  defp protect_local_avatars(%{path_info: ["images", "avatars" | _]} = conn, _) do
    conn |> fetch_session() |> PronotexWeb.Auth.call([])
  end

  defp protect_local_avatars(conn, _), do: conn
end
