// Regenerate iOS launch PNGs and their Phoenix template with Node.js and sharp.
const fs = require("node:fs/promises");
const path = require("node:path");
const sharp = require("sharp");
const root = path.resolve(__dirname, "..");
const destination = path.join(root, "priv/static/images/startup");
// CSS screen width, height, pixel ratio; full-screen portrait and landscape.
const screens = [
    [320, 568, 2], [375, 667, 2], [414, 736, 3],
    [375, 812, 3], [414, 896, 2], [414, 896, 3],
    [390, 844, 3], [393, 852, 3], [428, 926, 3], [430, 932, 3],
    [402, 874, 3], [420, 912, 3], [440, 956, 3],
    [768, 1024, 2], [744, 1133, 2], [810, 1080, 2],
    [820, 1180, 2], [834, 1112, 2], [834, 1194, 2],
    [834, 1210, 2], [1024, 1366, 2], [1032, 1376, 2],
];

async function main() {
  await fs.mkdir(destination, {recursive: true});
  const logos = new Map();
  for (const ratio of new Set(screens.map(screen => screen[2]))) {
    logos.set(ratio, await sharp(path.join(root, "priv/static/images/brand/pronotex-logo-detailed.svg"), {density: 96 * ratio})
      .resize(128 * ratio, 128 * ratio, {fit: "contain", background: "#00000000"})
      .png().toBuffer());
  }
  const links = ["<%!-- Generated by scripts/generate_startup_images.cjs. --%>"];
  for (const [width, height, ratio] of screens) {
    for (const orientation of ["portrait", "landscape"]) {
      const [w, h] = orientation === "portrait" ? [width, height] : [height, width];
      const filename = `launch-${w * ratio}x${h * ratio}.png`;
      await sharp({create: {width: w * ratio, height: h * ratio, channels: 3, background: "#3c987f"}})
        .composite([{input: logos.get(ratio), gravity: "centre"}])
        .png({compressionLevel: 9}).toFile(path.join(destination, filename));
      const media = `(device-width: ${width}px) and (device-height: ${height}px) and (-webkit-device-pixel-ratio: ${ratio}) and (orientation: ${orientation})`;
      links.push(`<link
  rel="apple-touch-startup-image"
  media="${media}"
  href={~p"/images/startup/${filename}"}
/>`);
    }
  }
  await fs.writeFile(path.join(root, "lib/pronotex_web/components/layouts/startup_images.html.heex"), links.join("\n") + "\n");
}
main().catch(error => { console.error(error); process.exitCode = 1; });
